#!/usr/bin/env bb

(require '[clojure.string :as str]
         '[clojure.java.io :as io]
         '[babashka.fs :as fs])

(def icons-dir "resources/public/komponentkassen/icons")
(def output-file "src/com/itonomi/komponentkassen/aksel_icons.cljc")

(defn svg-file->icon-name [file]
  (let [name (-> (.getName file)
                 (str/replace ".svg" ""))]
    ;; Handle reserved words
    (case name
      "Package" "PackageIcon"
      name)))

(defn parse-svg-attributes [attrs-str]
  (let [pairs (re-seq #"(\S+?)=\"([^\"]+)\"" attrs-str)]
    (into {} (map (fn [[_ k v]]
                    [(keyword k) v])
                  pairs))))

(defn escape-quotes [s]
  (str/replace s "\"" "\\\""))

(defn format-attribute-value [v]
  (escape-quotes v))

(defn format-attributes [attrs]
  (let [filtered-attrs (dissoc attrs :xmlns)]  ; Always omit xmlns
    (if (empty? filtered-attrs)
      ""
      (str "\n    (dom/props "
           (pr-str filtered-attrs)
           ")"))))

(defn parse-element [element-str]
  (when-let [[_ tag attrs-str] (re-matches #"<(\w+)([^>]*)/?>" element-str)]
    {:tag tag
     :attrs (-> (parse-svg-attributes attrs-str)
                (update :fill (fn [fill]
                                (when fill
                                  (if (= fill "#202733")
                                    "currentColor"
                                    fill))))
                (update :stroke (fn [stroke]
                                  (when stroke
                                    (if (= stroke "#202733")
                                      "currentColor"
                                      stroke))))
                (#(cond-> %
                    (nil? (:fill %)) (dissoc :fill)
                    (nil? (:stroke %)) (dissoc :stroke))))}))

(defn svg-content->electric [svg-content icon-name]
  (let [lines (str/split-lines svg-content)
        ;; Parse root svg element
        svg-line (first (filter #(str/starts-with? % "<svg") lines))
        svg-attrs (when svg-line
                    (:attrs (parse-element svg-line)))
        ;; Get all path/shape elements
        elements (filter #(re-find #"<(path|rect|circle|ellipse|line|polyline|polygon|g)" %) lines)
        parsed-elements (keep parse-element elements)]
    
    (str "(e/defn " icon-name " []\n"
         "  (svg/svg"
         (when svg-attrs
           (format-attributes svg-attrs))
         (when (seq parsed-elements)
           (str/join ""
                     (map (fn [{:keys [tag attrs]}]
                            (str "\n    (svg/" tag
                                 (format-attributes attrs)
                                 ")"))
                          parsed-elements)))
         "))")))

(defn generate-icons []
  (let [svg-files (filter #(str/ends-with? (.getName %) ".svg")
                           (file-seq (io/file icons-dir)))
        icons (sort-by #(.getName %)
                       svg-files)]
    
    ;; Create output directory if it doesn't exist
    (fs/create-dirs (fs/parent output-file))
    
    (spit output-file
          (str ";; Generated by generate-icons.bb\n"
               ";; Do not edit this file directly\n\n"
               "(ns com.itonomi.komponentkassen.aksel-icons\n"
               "  (:require [hyperfiddle.electric3 :as e]\n"
               "            [hyperfiddle.electric-dom3 :as dom]\n"
               "            [hyperfiddle.electric-svg3 :as svg]))\n\n"
               (str/join "\n\n"
                         (map (fn [file]
                                (let [icon-name (svg-file->icon-name file)
                                      svg-content (slurp file)]
                                  (svg-content->electric svg-content icon-name)))
                              icons))))
    
    (println (str "Generated " (count icons) " icons in " output-file))))

(generate-icons)